version: '3.8'

services:
  yolo_detector:
    build: .
    volumes:
      - ./images:/images:ro          # изображения
      - ./weights:/app/model:ro      # монтируем weights туда, где YOLO его ждёт
      - ./results:/app/results       # куда сохранять CSV
    working_dir: /app
    command: ["python", "detect_and_count.py"]
