version: '3.8'

services:
  yolo_detector:
    build: .
    volumes:
      - ./images:/images:ro
      - ./weights:/weights:ro
      - ./results:/app/results
    working_dir: /app
    # при запуске выполняется наш скрипт
    command: ["python", "detect_and_count.py"]
